# Generated by Django 5.1 on 2024-08-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_usuario_plataforma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario_plataforma',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
