# Generated by Django 5.1 on 2024-08-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_usuario_clave_usuario_plataforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('h2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('h4_text', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
