# Generated by Django 5.1 on 2024-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Imagen de Slider', 'verbose_name_plural': 'Imágenes de Slider'},
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto del Botón'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Botón'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='h2_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto H2'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='h4_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto H4'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Párrafo'),
        ),
    ]
