# Generated by Django 5.1 on 2024-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descripcionLarga',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='disponible',
            new_name='existencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoProducto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcionCorta',
            field=models.CharField(default='Descripción corta no disponible', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioOferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
