# Generated by Django 5.1 on 2024-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0011_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/mobile/', verbose_name='Imagen versión móvil'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='Imagen versión escritorio'),
        ),
    ]
